In [1]:
import torch
from botorch.test_functions import Ackley
from discrete_mixed_bo.problems.base import DiscretizedBotorchTestProblem

In [2]:
dim = 20
integer_bounds = torch.zeros(2, dim - 5)
integer_bounds[1, :5] = 2  # 3 values
integer_bounds[1, 5:10] = 4  # 5 values
integer_bounds[1, 10:15] = 9  # 10 values
ackley = Ackley(dim=dim, negate=True)
d_ackley = DiscretizedBotorchTestProblem(
    problem=ackley,
    integer_indices=list(range(dim - 5)),
    integer_bounds=integer_bounds,
)

In [3]:
d_ackley.bounds.T

tensor([[-32.7680,  32.7680],
        [-32.7680,  32.7680],
        [-32.7680,  32.7680],
        [-32.7680,  32.7680],
        [-32.7680,  32.7680],
        [  0.0000,   2.0000],
        [  0.0000,   2.0000],
        [  0.0000,   2.0000],
        [  0.0000,   2.0000],
        [  0.0000,   2.0000],
        [  0.0000,   4.0000],
        [  0.0000,   4.0000],
        [  0.0000,   4.0000],
        [  0.0000,   4.0000],
        [  0.0000,   4.0000],
        [  0.0000,   9.0000],
        [  0.0000,   9.0000],
        [  0.0000,   9.0000],
        [  0.0000,   9.0000],
        [  0.0000,   9.0000]])

In [4]:
d_ackley._orig_integer_indices

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
d_ackley._orig_categorical_indices

tensor([], dtype=torch.int64)

In [6]:
d_ackley._orig_cont_indices

tensor([15, 16, 17, 18, 19])

In [7]:
d_ackley._orig_bounds

tensor([[  0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,   0.0000,
           0.0000, -32.7680, -32.7680, -32.7680, -32.7680, -32.7680],
        [  2.0000,   2.0000,   2.0000,   2.0000,   2.0000,   4.0000,   4.0000,
           4.0000,   4.0000,   4.0000,   9.0000,   9.0000,   9.0000,   9.0000,
           9.0000,  32.7680,  32.7680,  32.7680,  32.7680,  32.7680]])

In [10]:
# if no categorical indices, one-hot bounds should be equal to bounds
torch.eq(d_ackley.one_hot_bounds.T, d_ackley.bounds.T).all()

tensor(True)